.TH NETMATE 1 "13 OCT 2016"

.SH "NAME"
netmate \- displays network protocol headers in uniform RFC like format

.SH "SYNOPSIS"
\fBnetmate\fP filename

.SH "DESCRIPTION"
Netmate is a GTK+ program that shows network protocols headers in 32-bit aligned fields, identical as they are represented in Request for Comments (RFCs).
It can be used to learn and teach about network protocols and to understand their functionality and collaboration.

This tool supports input files in pcap(ng) format as they are created by tcpdump, wireshark or other code based on libpcap.

Netmate is written in C and released under the GNU General Public License.
It was inspired by netdude, that is not further developed any more.

Currently the following network protocols are supported:
.br
\- Layer 2: Ethernet, SLL (Linux Cooked)
.br
\- Layer 3: ARP, ICMP, ICMPv6, IPv4, IPv6
.br
\- Layer 4: TCP, UDP

.SH "DEVELOPMENT"
This tool is still under development! Please send any further wishes, feature requests or problems in compiling and execution to ruport@f00l.de.
Also send me any more network protocols you want to be supported in future releases.

For further information visit the netmate homepage at http://f00l.de/netmate/.

.SH "HISTORY"
.TP 5
0.2.1 - 13.10.2016
* removed separate ICMP data fields with one single field
.br
* updated code to match GTK 3.10 requirements
.TP
0.2.0 - 17.11.2013
* added full support for neighbor discovery protocol (NDP)
.br
* fixed GPLv3 license statement and added to all files
.br
* minor bug fixes
.TP
0.1.9 - 10.11.2013
* added resolution of header fields for all supported protocols
.br
* minor bug fixes
.TP
0.1.8 - 28.10.2013
* added tooltips for all supported protocols
.br
* improved Makefile
.br
* minor bug fixes
.TP
0.1.7 - 19.10.2013
* improved Makefile
.br
* added shortcut and icon
.br
* added README and man-page
.br
* compiles under windows
.br
* minor bug fixes
.TP
0.1.6 - 05.10.2013
.br
* initial changelog
.br
* added columns source port, destination port, flags
.br
* columns are resizable now
.br
* removed external GUI (netmate.ui)
.br
* minor fixes

.SH "COPYRIGHT"
Copyright (c) 2013-2016 Robert Krause

Netmate is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.

Netmate is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.SH "AUTHOR"
Written by Robert Krause <ruport@f00l.de>.
