/* LAYER 2 */

/* ETHERNET */
#define ETHERNET_DESTINATION "Destination MAC Address\n\nEthernet and IEEE 802.3 addresses are 6 bytes long. Addresses are contained in hardware on the Ethernet and IEEE 802.3 interface cards. The first 3 bytes of the addresses are specified by the IEEE on a vendor-dependent basis, while the last 3 bytes are specified by the Ethernet or IEEE 802.3 vendor. The source address is always a unicast (single node) address, while the destination address may be unicast, multicast (group), or broadcast (all nodes).\n\n[IEEE 802.3]"
#define ETHERNET_SOURCE "Source MAC Address\n\nEthernet and IEEE 802.3 addresses are 6 bytes long. Addresses are contained in hardware on the Ethernet and IEEE 802.3 interface cards. The first 3 bytes of the addresses are specified by the IEEE on a vendor-dependent basis, while the last 3 bytes are specified by the Ethernet or IEEE 802.3 vendor. The source address is always a unicast (single node) address, while the destination address may be unicast, multicast (group), or broadcast (all nodes).\n\n[IEEE 802.3]"
#define ETHERNET_TYPE "Protocol Type\n\nThis field specifies the upper-layer protocol to receive the data after Ethernet processing is complete.\n\n[IEEE 802.3]"

/* SLL (Linux Cooked) */
#define SLL_PACKET_TYPE "Packet Type\n\nThe packet type field is in network byte order (big-endian); it contains a value that is one of:\n\t0, if the packet was specifically sent to us by somebody else;\n\t1, if the packet was broadcast by somebody else;\n\t2, if the packet was multicast, but not broadcast, by somebody else;\n\t3, if the packet was sent to somebody else by somebody else;\n\t4, if the packet was sent by us.\n\n[www.tcpdump.org]"
#define SLL_ARPHRD_TYPE "ARPHRD_ Type\n\nThe ARPHRD_ type field is in network byte order; it contains a Linux ARPHRD_ value for the link-layer device type.\n\n[www.tcpdump.org]"
#define SLL_LLA_LENGTH "Link-layer Address Length\n\nThe link-layer address length field is in network byte order; it contains the length of the link-layer address of the sender of the packet. That length could be zero.\n\n[www.tcpdump.org]"
#define SLL_LLA "Link-layer Address\n\nThe link-layer address field contains the link-layer address of the sender of the packet; the number of bytes of that field that are meaningful is specified by the link-layer address length field. If there are more than 8 bytes, only the first 8 bytes are present, and if there are fewer than 8 bytes, there are padding bytes after the address to pad the field to 8 bytes.\n\n[www.tcpdump.org]"
#define SLL_PROTOCOL "Protocol Type\n\nThe protocol type field is in network byte order; it contains an Ethernet protocol type, or one of:\n\t1, if the frame is a Novell 802.3 frame without an 802.2 LLC header;\n\t4, if the frame begins with an 802.2 LLC header.\n\n[www.tcpdump.org]"
